name: 4. Build Loop Follow for 2 Children
run-name: Build Loop Follow for 2 Children  (${{ github.ref_name }})
on:
  workflow_dispatch:

  ## Remove the "#" sign from the beginning of the line below to get automated builds on push (code changes in your repository)
  #push:

  ## Remove the "#" sign from the beginning of the two lines below to get automated builds every two months
  #schedule:
    #- cron: '0 17 1 */2 *' # Runs at 17:00 UTC on the 1st in Jan, Mar, May, Jul, Sep and Nov.

env:
  TEAMID: ${{ secrets.TEAMID }}
  GH_PAT: ${{ secrets.GH_PAT }}
  FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
  FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
  FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

jobs:
#  secrets:
#    uses: ./.github/workflows/validate_secrets.yml
#    secrets: inherit

  build:
#    needs: secrets
    runs-on: macos-12
    steps:
      # Uncomment to manually select latest Xcode if needed
      - name: Select Latest Xcode
        run: "sudo xcode-select --switch /Applications/Xcode_14.1.app/Contents/Developer"

      # Checks-out the repo
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      # Patch Fastlane Match to not print tables
      - name: Patch Match Tables
        run: find /usr/local/lib/ruby/gems -name table_printer.rb | xargs sed -i "" "/puts(Terminal::Table.new(params))/d"
      
      # Build signed Loop Follow  for child 1 IPA file
      - name: Fastlane Build & Archive
        run: fastlane build_LoopFollow
        env:
          APP_SCHEME: "loopfollowChild1"
          APP_ID: "loopfollowChild1"
          CONFIGURATION: "Debug" # "Debug" or "Release"
      
      # Upload Loop Follow for child 1 to TestFlight
      - name: Fastlane upload to TestFlight
        run: fastlane release
        env:
          APP_SCHEME: "loopfollowChild1"
          
      # Build signed Loop Follow for child 2 IPA file
      - name: Fastlane Build & Archive
        run: fastlane build_LoopFollow
        env:
          APP_SCHEME: "loopfollowChild2"
          APP_ID: "loopfollowChild2"
          CONFIGURATION: "Debug" # "Debug" or "Release"
      
      # Upload Loop Follow for child 2 to TestFlight
      - name: Fastlane upload to TestFlight
        run: fastlane release
        env:
          APP_SCHEME: "loopfollowChild2"

      # Upload IPA and Symbols
      - name: Upload IPA and Symbol artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            artifacts
            buildlog
